---
title: "BikeSpace Dashboard Report"
output: 
  pdf_document:
    keep_tex: yes
always_allow_html: yes
params:
  data: NA
  date_1: NA
  date_2: NA
  dur_input: NA
  prob_input: NA
  street_input: NA
  intersection_input: NA
  zoom: NA
---

## Data Filters Applied

```{r echo=FALSE, message=FALSE, warning=FALSE}
#------------------------#
#    User Input Table    #
#------------------------#

# Create dataframe of inputs
input_names <- list("Date Range", "Parking Duration", "Problem Type", "Street",
                    "Intersection", "Total Number of Reports")

report_num <- nrow(params$data)

date_range <- paste(params$date_1, "-", params$date_2, sep = " ")

input_user <- list(date_range, params$dur_input, params$prob_input, params$street_input,
                   params$intersection_input, report_num)

input_df <- cbind(input_names, input_user)
colnames(input_df) <- c("Data Filters", "User Input")
```

```{r echo=FALSE, message=FALSE, results='asis'}
library(knitr)
kable(input_df)
```

## User Submitted Issues

```{r echo=FALSE, message=FALSE, warning=FALSE}
#------------------------#
#         Map            #
#------------------------#

library(leaflet)
library(htmltools)

devtools::install_github("wch/webshot")
webshot::install_phantomjs()

prob_choices <- nrow(data.frame(unlist(params$data[,"problem_type"])))

# Parameters for MapBox basemap
street_map <- "https://api.mapbox.com/styles/v1/arielag/cjhl8uwjg084r2sopg0stjoob/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiYXJpZWxhZyIsImEiOiJjamY1dTlseDYxZHB0Mnlsbndsb3BkaTV5In0.SiiSe0JU0cXc6sqeLA4Hcg"
  
map_attr <- "© <a href='https://www.mapbox.com/map-feedback/'>Mapbox</a>"

if(prob_choices > 0){
      m1 <- leaflet(params$data) %>% 
        addTiles(urlTemplate = street_map, attribution = map_attr) %>%
        addMarkers(lng = ~problem_long, lat = ~problem_lat, 
                   clusterOptions = markerClusterOptions()) %>%
        setView(lng = -79.3892, lat = 43.6426, zoom = params$zoom)
    } else{
      m1 <- leaflet() %>% 
        addTiles(urlTemplate = street_map, attribution = map_attr) %>%
        setView(lng = -79.3892, lat = 43.6426, zoom = params$zoom)
    }

m1

```

## Problem Type Frequency

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#------------------------#
#   Problem Type Chart   #
#------------------------#

library(highcharter)
library(dplyr)

unlist_df <- data.frame(unlist(params$data[,"problem_type"]))

probtype_df <- if(nrow(unlist_df) > 0){
      colnames(unlist_df) <- c("problem_type")
      unlist_df %>%
        count(problem_type) %>%
        arrange(desc(n)) %>%
        slice(1:6)
    } else{
      return()
    }
  
n_colors <- nrow(probtype_df)

ptbar_data <- if(prob_choices > 0){
      if(n_colors == 6){
        probtype_df %>%
          mutate(x = row_number()) %>%
          mutate(color = c("#ff0000", "#ff3300", "#fcb600", "#f2f200", "#9ba39d", "#46e08c")) %>%
          rename(name = problem_type,
                 y = n) %>% 
          select(y, name, color) %>% 
          list.parse3()
      } else if(n_colors == 5){
        probtype_df %>%
          mutate(x = row_number()) %>%
          mutate(color = c("#ff0000", "#ff3300", "#fcb600", "#f2f200", "#46e08c")) %>%
          rename(name = problem_type,
                 y = n) %>% 
          select(y, name, color) %>% 
          list.parse3()
      } else if(n_colors == 4){
        probtype_df %>%
          mutate(x = row_number()) %>%
          mutate(color = c("#ff0000", "#fcb600", "#f2f200", "#46e08c")) %>%
          rename(name = problem_type,
                 y = n) %>% 
          select(y, name, color) %>% 
          list.parse3()
      } else if(n_colors == 3){
        probtype_df %>%
          mutate(x = row_number()) %>%
          mutate(color = c("#ff0000", "#f2f200", "#46e08c")) %>%
          rename(name = problem_type,
                 y = n) %>% 
          select(y, name, color) %>% 
          list.parse3()
      } else if(n_colors == 2){
        probtype_df %>%
          mutate(x = row_number()) %>%
          mutate(color = c("#ff3300", "#46e08c")) %>%
          rename(name = problem_type,
                 y = n) %>% 
          select(y, name, color) %>% 
          list.parse3()
      } else{
        probtype_df %>%
          mutate(x = row_number()) %>%
          mutate(color = c("#00cb47")) %>%
          rename(name = problem_type,
                 y = n) %>% 
          select(y, name, color) %>% 
          list.parse3()
      }
    } else{
      return()
    }

bar_chart <- highchart() %>% 
      hc_xAxis(type="category", lineColor = "#ffffff", tickColor = "#ffffff") %>%
      hc_yAxis(title = "Blank", visible = FALSE) %>% 
      hc_add_series(data = ptbar_data, type = "bar", showInLegend = FALSE,
                    name = "Frequency") %>%
      hc_plotOptions(bar = list(
        dataLabels = list(
          align = "left",
          enabled = TRUE,
          crop = FALSE,
          overflow = "none"
        ))
      )

bar_chart
```

## Frequency By Day

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#------------------------#
#  Daily Frequency Chart #
#------------------------#

weekcol_df <- data.frame(c("Sun", "Mon", "Tue", "Wed",
                             "Thu", "Fri", "Sat"))
colnames(weekcol_df) <- c("weekday")
  
# Create frequency count from data by weekday, dropping NAs
weekcol_data <- params$data %>%
      count(weekday) %>%
      ungroup() %>%
      drop_na()
  
# Join data with dataframe for all weekdays
weekcol_df2 <- merge(weekcol_df, weekcol_data, all.x = TRUE, by=c("weekday"))
  
days_range <- max(params$data[,"date"], na.rm = TRUE) - min(params$data[,"date"], na.rm = TRUE)
  
# Convert the dataframe to a series for plotting
weekcol_chart_data <- if(days_range > 5){
      weekcol_df2 %>%
        replace_na(list(weekday = NA, n = 0)) %>%
        arrange(factor(weekday, levels = c("Sun", "Mon", "Tue", "Wed",
                                           "Thu", "Fri", "Sat"))) %>%
        mutate(x = row_number()) %>%
        mutate(color = c("#00cb47")) %>%
        rename(name = weekday, 
               y = n) %>% 
        select(y, name, color) %>% 
        list.parse3()
    } else if(days_range > -Inf){
      params$data %>%
        count(date) %>%
        mutate(date2 = datetime_to_timestamp(date)) %>%
        drop_na()
    } else{
      return()
    }
  
# Create the frequency plot
weekcol_chart <- if(days_range > 5 | days_range == -Inf){
      highchart() %>% 
        hc_xAxis(type="category", lineColor = "#ffffff", tickColor = "#ffffff") %>%
        hc_yAxis(title = "Blank", visible = FALSE) %>% 
        hc_add_series(data = weekcol_chart_data, type = "column", showInLegend = FALSE,
                      name = "Frequency") %>%
        hc_plotOptions(column = list(
          dataLabels = list(
            align = "center",
            enabled = TRUE,
            crop = FALSE,
            overflow = "none"
          ))
        )
    } else{
      highchart() %>%
        hc_xAxis(type = "datetime", dateTimeLabelFormats = list(day = '%d of %b'), 
                 lineColor = "#ffffff", tickColor = "#ffffff") %>%
        hc_yAxis(title = "Blank", visible = FALSE) %>%
        hc_add_series(weekcol_chart_data, "column", hcaes(date, n), 
                      showInLegend = FALSE, name = "Frequency") %>%
        hc_plotOptions(column = list(
          color = "#00cb47",
          dataLabels = list(
            align = "center",
            enabled = TRUE,
            crop = FALSE,
            overflow = "none"
          ))
        )
    }

weekcol_chart
```

## Type of Bike Parking Demand by Time of Day

```{r, echo=FALSE, message=FALSE, warning=FALSE}
#------------------------#
#       Heat Map         #
#------------------------#

# Generate dataframe with all possible time v. duration combinations
hours <- c("6am - 9am", "10am - 12pm", "1pm - 4pm", "5pm - 7pm", "8pm +")
heat_hours <- sort(rep(hours,3))
heat_duration <- rep(c("short", "med", "long"), 5)
  
heat_df <- data.frame(heat_hours, heat_duration)
colnames(heat_df) <- c("time_group", "duration")
  
# Create frequency count by hour and parking duration from data, dropping NAs
heat_count <- params$data %>%
      group_by(time_group, duration) %>%
      summarise(count = n()) %>%
      ungroup() %>%
      drop_na()
  
# Merge the frequncy count with the dataframe with all hours and parking duration combinations  
heat_data <- merge(heat_df, heat_count, all.x = TRUE, by=c("time_group", "duration"))
  
heat_data_2 <- heat_data %>%
      replace_na(list(time_group = NA, duration = NA, count = 0)) %>%
      arrange(factor(time_group, levels = c("6am - 9am", "10am - 12pm", "1pm - 4pm",
                                            "5pm - 7pm", "8pm +")), 
              factor(duration, levels = c("short", "med", "long")))
  
# Prepare values for the axes of the heat map
y <- c("Short", "Medium", "Long")
x <- c("6am - 9am", "10am - 12pm", "1pm - 4pm", "5pm - 7pm", "8pm +")
  
# Convert the dataframe to a series for plotting
heat_data_series <- heat_data_2 %>%
      mutate(yid = rep(c(0,1,2),5),
             xid = sort(rep(seq(1:5)-1,3))) %>%
      select(xid, yid, count) %>%
      list.parse2()
  
# Create color gradient for the heat map
freq_colr <- list(list(0, '#ffffff'),
                    list(0.20, '#46e08c'),
                    list(0.40, '#f2f200'),
                    list(0.60, '#fcb600'),
                    list(0.80, '#ff3300'),
                    list(1.0, '#ff0000'))
  
# Create the heat map
heat_map <- highchart() %>% 
      hc_chart(type = "heatmap") %>% 
      hc_xAxis(categories = x) %>% 
      hc_yAxis(categories = y) %>% 
      hc_add_series(data = heat_data_series) %>% 
      hc_plotOptions(
        series = list(
          boderWidth = 0,
          dataLabels = list(enabled = TRUE)
        )) %>% 
      hc_legend(align = "right", layout = "vertical",
                margin = 0, verticalAlign = "top",
                symbolHeight = 500, itemMarginTop = 5) %>% 
      hc_colorAxis(stops= freq_colr, showInLegend = FALSE)

heat_map
```




